apiVersion: apps/v1
kind: Deployment
metadata:
  name: vicrori
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vicrori
  template:
    metadata:
      labels:
        app: vicrori
    spec:
      containers:
      - image: okteto.dev/vicrori:latest
        name: vicrori
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/LandingStartups-html.zip"
        - name: Vless_UUID
          value: "03d0f50e-6766-4bea-a77d-262585d9f50c"
        - name: Vless_Path
          value: "/03d0f50e-6766-4bea-a77d-262585d9f50c-vless"
        - name: Vmess_UUID
          value: "03d0f50e-6766-4bea-a77d-262585d9f50c"
        - name: Vmess_Path
          value: "/03d0f50e-6766-4bea-a77d-262585d9f50c-vmess"
        - name: Share_Path
          value: "/v5errnk"
